steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/qwiklabs-gcp-02-46d4ee94259d/my-repository/sample-app:v2.0', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/qwiklabs-gcp-02-46d4ee94259d/my-repository/sample-app:v2.0']

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/production-deployment'
  - 'production-container=europe-west1-docker.pkg.dev/qwiklabs-gcp-02-46d4ee94259d/my-repository/sample-app:v2.0'
  - '-n'
  - 'prod'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
