apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: development-deployment
  template:
    metadata:
      labels:
        app: development-deployment
    spec:
      containers:
      - name: development-deployment
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-02-81aa819a1925/my-repository/sample-app:v2.0
        ports:
        - containerPort: 8080
